  
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controllers\HomeController::homePage
category:
    path: /categorie
    controller: App\Controllers\CategoriesController::showCategorie