on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1 # or alternative dependency management
      - uses: php-actions/phpunit@v9
        with:
          # If there isn't a PHPUnit config, specify files or directories to test
          configuration: phpunit.xml
          args: --coverage-text