name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Run phpunit
        run: ./vendor/bin/phpunit-watcher
      - name: Run phpcs
        run: ./vendor/bin/phpcs
       